### ISSUE TITLE
Support basic authentification

### ISSUE THREAD

**Issue by raspbeguy** [maxammann/music-cyclon#1]
I've got a beets server behind a HTTPS Nginx reverse proxy with basic authentification setting. I cannot access it with the app, I tried to type the URL with the syntax `https://user:password@server.tld`.
On server logs, I can see it tried to log without any authentification items, resulting to a 401 error.

**Comment by maxammann** [comment]
Going to look into it. There is also another issue at the moment. A pending pull request: https://github.com/beetbox/beets/pull/2050

**Comment by nico202** [comment]
Years later I added basic support for it. Password is saved in clear text but for me it's enough, see PR  #4

**Comment by maxammann** [comment]
This has been implemented in PR #4 Thanks @nico202 :)
