### ISSUE TITLE
Pending pull request for beets

### ISSUE THREAD

**Issue by maxammann** [maxammann/music-cyclon#2]
https://github.com/beetbox/beets/pull/2050

**Comment by b-harper** [comment]
Can this issue be closed?  The changes from [2050][0] were released in [beets 1.4.1][1].


[0]: https://github.com/beetbox/beets/pull/2050
[1]: https://github.com/beetbox/beets/releases/tag/v1.4.1

**Comment by maxammann** [comment]
Uhm jup :)

**Comment by maxammann** [comment]
Uhm, nope :D I haven't implemented the changes in music-cyclon yet. Should get next month some time to fix this :/

**Comment by maxammann** [comment]
Thanks to @nico202 for the fix. This can be closed now.
